#!/usr/bin/zsh

# https://github.com/AlphaKeks

alias ls='/bin/ls --color=auto -Hl'
alias la='ls -A'
alias grep='grep --color=auto'
alias mkdir='mkdir -p'
alias fucking='doas'
alias cls='clear && neofetch'
alias cya='loginctl poweroff now'
alias reboot='loginctl reboot'
alias pacman='doas pacman'
alias remove-orphans='fucking pacman -R $(pacman -Qtdq)'
alias clear='tput reset'

alias rm='rm -I'
alias ..='cd ..'

alias vim='nvim'
alias nrs='npm run start'
alias lg='lazygit'
alias g='git'
alias gs='git status'
alias make='make -j 30'
alias ghr='cd $HOME/git/hub/repos'
alias glr='cd $HOME/git/lab/repos'
alias df='cd ~/.dotfiles'
alias rain='cmatrix -u 10 -C blue -o -m'
alias aci='arduino-cli'

alias dl3='yt-dlp -x --audio-format mp3'
alias dl4='yt-dlp -f mp4'

alias ssh:schnose='ssh max@schnose'
alias ssh:vpn='ssh root@45.81.234.77'

alias md='lookatme --live-reload --style gruvbox-dark'

gc () {
	repo=$(bash -c 'read -e -p "which repo would you like to clone? " tmp; echo $tmp')
	git clone git@github.com:$repo $repo
}

unpack () {
	if [ -f $1 ] ; then
		case $1 in
			*.tar.bz2)   tar xjf $1   ;;
			*.tar.gz)    tar xzf $1   ;;
			*.bz2)       bunzip2 $1   ;;
			*.rar)       unrar x $1   ;;
			*.gz)        gunzip $1    ;;
			*.tar)       tar xf $1    ;;
			*.tbz2)      tar xjf $1   ;;
			*.tgz)       tar xzf $1   ;;
			*.zip)       unzip $1     ;;
			*.Z)         uncompress $1;;
			*.7z)        7z x $1      ;;
			*.deb)       ar x $1      ;;
			*.tar.xz)    tar xf $1    ;;
			*.tar.zst)   tar xf $1    ;;
			*)           echo "'$1' cannot be extracted." ;;
		esac
	else
    echo "'$1' is not a valid file."
	fi
}

alias pack='tar -czvf'
