#!/usr/bin/zsh

# https://github.com/AlphaKeks

export EDITOR='nvim'
export TERM='kitty'
export BROWSER='librewolf'
export SCHNOSE='(͡ ͡° ͜ つ ͡͡°)'
export FZF_DEFAULT_OPTS='--color=bg+:#302D41,bg:#1E1E2E,spinner:#F8BD96,hl:#F28FAD --color=fg:#D9E0EE,header:#F28FAD,info:#DDB6F2,pointer:#F8BD96 --color=marker:#F8BD96,fg+:#F2CDCD,prompt:#DDB6F2,hl+:#F28FAD'
export GTK_THEME=Catppuccin-blue:dark
