edition = "2021"

max_width = 100
array_width = 80
chain_width = 80
fn_call_width = 80
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100

hard_tabs = true
tab_spaces = 4

match_block_trailing_comma = true
newline_style = "Unix"
use_field_init_shorthand = true
