#!/bin/sh

# https://github.com/AlphaKeks

pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-kde-authentication-agent-1 &

bspc monitor DisplayPort-0 -d "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X" # middle
bspc monitor DisplayPort-1 -d discord signal nextcloud "IV" "V" "VI" "VII" "VIII" "IX" "X"  # left
bspc monitor DisplayPort-2 -d "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X" # top
bspc monitor HDMI-A-0 -d "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X"      # right

xrandr --output DisplayPort-0 --mode 1920x1080 --rate 240.30 --primary --dpi 96
xrandr --output DisplayPort-1 --mode 1920x1080 --rate 60.00 --dpi 96 --left-of DisplayPort-0
xrandr --output DisplayPort-2 --mode 1920x1080 --rate 60.00 --dpi 96 --above DisplayPort-0
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 60.00 --dpi 96 --right-of DisplayPort-0

bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config focus_follows_pointer true
bspc config normal_border_color \#181825
bspc config active_border_color \#181825
bspc config focused_border_color \#a6adc8

bspc rule -a Galculator state=floating
bspc rule -a Bitwarden state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a KeyOverlay state=floating
bspc rule -a Thunar state=floating
bspc rule -a Gthumb state=floating
bspc rule -a nitrogen state=floating
bspc rule -a showmethekey-gtk state=floating

bspc rule -a discord desktop=discord
bspc rule -a discord-screenaudio desktop=discord
bspc rule -a Signal desktop=signal
bspc rule -a schnosecloud-nativefier-51a909 desktop=nextcloud

# corners for floating windows
corners() {
	bspc subscribe node_state | while read -r _ _ _ node state status; do
		if [[ "$state" == "floating" ]]; then
			case "$status" in
				off) xprop -id "$node" -remove _PICOM_CORNERS;;
				on) xprop -id "$node" -f _PICOM_CORNERS 32c -set _PICOM_CORNERS 1;;
			esac
		fi
	done
}
corners &

/usr/bin/xsetroot -cursor_name left_ptr &
/usr/bin/nitrogen --restore &
/usr/bin/picom -b --config $HOME/.config/picom/picom.conf &
/usr/bin/dunst &
/usr/bin/screencloud &
/usr/bin/easyeffects --gapplication-service &
/usr/bin/corectrl --minimize-systray &

$HOME/.config/polybar/launch.sh &
/usr/bin/signal-desktop &
# /usr/bin/discord &
/usr/bin/discord-screenaudio &
$HOME/.local/bin/schnoseCloud-linux-x64/schnoseCloud &
/usr/bin/steam -silent &
/usr/bin/nextcloud &

rm -rf $HOME/tmp/*
