#!/bin/sh

# https://github.com/AlphaKeks

# Inizialize sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9									#main
bspc monitor DisplayPort-1 -d Discord Signal Mail 4 5 6 7 8 9		#left
bspc monitor DisplayPort-2 -d "Home sweet ~" "VM" 3 4 5 6 7 8 9	#top
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9											#right

# Global CFG
bspc config border_width					1
bspc config window_gap						0
bspc config split_ratio						0.5
bspc config borderless_monocle		false
bspc config focus_follows_pointer	false
bspc config normal_border_color		\#161926
bspc config focused_border_color	\#7480C2
wmname "LG3D"

# Floating exceptions
bspc rule -a gnome-calculator			state=floating
bspc rule -a Bitwarden						state=floating
bspc rule -a pavucontrol					state=floating
bspc rule -a KeyOverlay						state=floating
bspc rule -a kzfeed								state=floating

# Cursor
xsetroot -cursor_name left_ptr &

# Autostart
bspc rule -a discord monitor=DisplayPort-1 desktop=Discord
bspc rule -a Signal monitor=DisplayPort-1 desktop=Signal
bspc rule -a thunderbird monitor=DisplayPort-1 desktop=Mail

$CFG/bspwm/scripts/services.sh &
$CFG/bspwm/scripts/desktop.sh &
$CFG/bspwm/scripts/corners.sh &
$CFG/bspwm/scripts/background.sh &
$CFG/bspwm/scripts/applications.sh &
